### ISSUE TITLE
Dealing with custom JJTree AST classes

### ISSUE THREAD

**Issue by jponge** [johnmartel/javaccPlugin#13]
This plugin generates _all_ classes for JJTree.

It is desirable to let developers write custom AST classes for _some_ JJTree elements.

This plugin should detect and remove generated duplicates, which is the behaviour of the [JavaCC Maven plugin](http://mojo.codehaus.org/javacc-maven-plugin/).

Otherwise the generated classes and custom classes are in conflict at compilation time, resulting in duplicate class errors.

**Comment by jponge** [comment]
Any update on this issue?

**Comment by johnmartel** [comment]
Sorry, I am working on this project on my spare time. With the Easter holiday coming, I should be able to release a new version fixing this issue. I had a look at the maven plugin and will provide similar functionality.

Please feel free to provide an example on your setup. My initial plan is to have the custom AST classes sit right where they should be in the sourceSet and to avoid generating matching classes in compileJavacc task.

Regards,

John

**Comment by jponge** [comment]
No worries :-)

We have a setup like that in golo-lang/golo-lang if you want to have a look, where some of the classes are overridden by us.

**Comment by p-muessig** [comment]
I solved this problem by adding

// Copying our node classes prevents JJTree from generating its own implementations
// of these classes.
// It seems that javaccPlugin 2.1.1 will address this issue.
task(copyJjtree, type: Copy) {
    from compileJjtree.inputDirectory
    into compileJjtree.outputDirectory
    include '**/*.java'
}
compileJjtree.dependsOn copyJjtree

to 'build.gradle' as a workaround until it is sovled in 'javaccPlugin'.

Regards,
Peter

**Comment by jponge** [comment]
Still no fix in sight?

**Comment by johnmartel** [comment]
Fix is coming in slowly, custom AST classes are now supported when they live directly with the JavaCC source code. I'm working on supporting them in the Java sourcesets as well.

**Comment by jponge** [comment]
Thanks @johnmartel for fixing it. I will shortly try it on eclipse/golo-lang
