### ISSUE TITLE
issues eclipse plugin

### ISSUE THREAD

**Issue by mdeanda** [johnmartel/javaccPlugin#14]
is there a way to have the eclipse plugin automatically pull in the generated folder? the package structure in generated isn't such that it would make it easy.

**Comment by johnmartel** [comment]
Not sure if this is what you meant, you will need to provide a better description of your problem if that is not the case: this is documented on the README page:

> If you are using Eclipse and would like your gradle project to compile nicely in eclipse and have the generated code in the build path, you can simply add the generated path to the main sourceSet and add a dependency on compileJavacc to eclipseClasspath.
> 
> ```
> main {
>    java {
>        srcDir compileJavacc.outputDirectory
>    }
> }
>
> eclipseClasspath.dependsOn("compileJavacc")
> ```
