### ISSUE TITLE
Generating different java packages from jjt files in the same project

### ISSUE THREAD

**Issue by dpolivaev** [johnmartel/javaccPlugin#21]
I have a project with 3 jjt files each of them produces an own parser in its own package. JavaccPlugin generates code for all of them in the same directories (build/generated/jjtree and build/generated/javacc) so that Node.java, SimpleNode.java, Token.java, TokenMgrError.java, ParseException.java and SimpleCharStream.java are overwritten by each following generation. I have found noi way to let the plugin generate files from different packages in different output directories and ended with writing my own gradle plugin for the same task. 

How can this problem be solved by your plugin?

Kind regards,
Dimitry

**Comment by johnmartel** [comment]
Hi Dimitry, can you please provide some examples of your .jjt files and how you configure the compileJjtree task. It helps definig exactly what the problem is. Meanwhile I'll have a look later today.

Thanks

**Comment by dpolivaev** [comment]
Hi John, 

files can not be attached to github issues.
How can I send you my bug report project?

Regards

**Comment by dpolivaev** [comment]
https://www.dropbox.com/s/57504x75yph9uma/javaccPluginTest.rar?dl=0

**Comment by johnmartel** [comment]
@dpolivaev I just went over the case, and while there was a missing test for this feature, this is working as expected. Just put your `.jjt` files inside packages, and of course declare the package in each file. See commit 08bfbe0 for an example.

**Comment by dpolivaev** [comment]
Great, thank you
